<div class="row">
    <div class="col-md-6">
        <form class="form-horizontal" role="form" method="post" autocomplete="off">
            <div class="form-group">
                <label for="adminUsername" class="col-sm-4 control-label">Admin</label>

                <div class="col-sm-8">
                    <input type="text" class="form-control" id="adminUsername" name="adminUsername" placeholder="Username" value="<?php echo $this->adminUsername; ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="adminPassword" class="col-sm-4 control-label">Admin</label>

                <div class="col-sm-8">
                    <input type="password" class="form-control" id="adminPassword" name="adminPassword" placeholder="Password" value="<?php echo $this->adminPassword; ?>">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <button type="submit" class="btn btn-default">save</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <?php if(!is_null($this->errors)): ?>
            <ul class="bg-danger">
                <?php foreach($this->errors as $error): ?>
                    <li><?php echo $error; ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>

