<div class="page-header">
    <h1>Flex
        <small>Error</small>
    </h1>
</div>


<?php if(!is_null($this->exception) && $this->exception instanceof \Exception): ?>
    <h2>Additional information:</h2>
    <h3><?php echo get_class($this->exception); ?></h3>

    <dl>
        <dt>File:</dt>
        <dd>
            <pre class="prettyprint"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
        </dd>
        <dt>Message:</dt>
        <dd>
            <pre class="prettyprint"><?php echo $this->exception->getMessage() ?></pre>
        </dd>
        <dt>Stack trace:</dt>
        <dd>
            <pre class="prettyprint"><?php echo $this->exception->getTraceAsString() ?></pre>
        </dd>
    </dl>

    <?php $e = $this->exception->getPrevious(); ?>
    <?php if($e): ?>
        <hr />
        <h2>Previous exceptions:</h2>
        <ul>
            <?php while($e): ?>
                <li>
                    <h3><?php echo get_class($e); ?></h3>
                    <dl>
                        <dt>File:</dt>
                        <dd>
                            <pre class="prettyprint"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                        </dd>
                        <dt>Message:</dt>
                        <dd>
                            <pre class="prettyprint"><?php echo $e->getMessage() ?></pre>
                        </dd>
                        <dt>Stack trace:</dt>
                        <dd>
                            <pre class="prettyprint"><?php echo $e->getTraceAsString() ?></pre>
                        </dd>
                    </dl>
                </li>
                <?php $e = $e->getPrevious(); endwhile; ?>
        </ul>
    <?php endif; ?>
<?php endif ?>