<div class="page-header">
    <h1>Powerpos <?php echo \Powerpos\Version::getVersion(); ?>
        <small>point of sale management system</small>
    </h1>
</div>

<form class="form-login" role="form" method="post">
    <h2 class="form-login-heading">please login</h2>
    <input type="email" name="email" class="form-control" placeholder="email address" required="" autofocus="">
    <input type="password" name="password" class="form-control" placeholder="password" required="">
    <label class="checkbox">
        <input type="checkbox" value="remember-me"> remember me
    </label>
    <button class="btn btn-lg btn-primary btn-block" type="submit">login</button>
</form>