<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">

    <title>elnebuloso / powerpos</title>

    <link rel="stylesheet" type="text/css" href="/vendor/sencha/ext/4.2.1-gpl/resources/css/ext-all.css">
    <script type="text/javascript" src="/vendor/sencha/ext/4.2.1-gpl/ext-debug.js"></script>
    <script type="text/javascript" src="/ext/application/app.js"></script>

</head>

<body>

<div class="container">
    <?php echo $this->content; ?>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- javascript -->
<!-- placed at the end of the document so the pages load faster -->
</body>
</html>