<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">

    <title>elnebuloso / powerpos</title>

    <link rel="stylesheet" href="/vendor/twitter/bootstrap/3.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="/vendor/twitter/bootstrap/3.1.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/vendor/twitter/bootstrap/3.1.0/css/dashboard.css">
    <link rel="stylesheet" href="/css/login.css">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/vendor/afarkas/html5shiv/3.7.0/html5shiv.min.js"></script>
    <script src="/vendor/scottjehl/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="container">
    <?php echo $this->content; ?>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- javascript -->
<!-- placed at the end of the document so the pages load faster -->
<script src="/vendor/jquery/jquery/1.10.2/jquery-1.10.2.min.js"></script>
<script src="/vendor/twitter/bootstrap/3.1.0/js/bootstrap.min.js"></script>
</body>
</html>